name: ROS CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  docs_no_ros:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_no_ros --tag r2r_no_ros
    - run: docker run r2r_no_ros cargo build --features doc-only

  tests_humble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_humble --tag r2r_humble
    - run: docker run r2r_humble cargo test

  tests_galactic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_galactic --tag r2r_galactic
    - run: docker run r2r_galactic cargo test

  tests_foxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_foxy --tag r2r_foxy
    - run: docker run r2r_foxy cargo test
